name: "CI (Integração Contínua): Main Workflow"

env:
    # Necessario gerar um token na vercel
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
on: 
    pull_request:
        branches: [ "main" ]

jobs:
    linter:
        runs-on: "ubuntu-latest"

        steps: 
            - uses: actions/checkout@v3
            
            # Roda a instalação das dependências do projeto
            - name: Run Installation
              run: npm install
            # Roda um comando simples usando o shell de execução
            - name: Run Linter
              run: npm run lint
    preview:
        runs-on: "ubuntu-latest"
        steps: 
            - uses: actions/checkout@v3
            # Roda a instalação das dependências do projeto
            - name: Run Installation
              run: npm install
            # Roda um comando simples usando o shell de execução, o comando gera um preview do site fora de produção com o deploy:staging
            - name: Run Preview Deployment
              run: npm run deploy:preview
    test_e2e:
        runs-on: "ubuntu-latest"
        steps: 
            - uses: actions/checkout@v3
            - uses: actions/checkout/node@v3
              with:
                node-version: 16.13.0
                cache: 'npm'
            # Install npm dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                build: npm run build
                start: npm start
                browser: chrome

    